mysite/blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView, about


app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='delete'),
    path('post/new/', PostCreateView.as_view(), name='create'),
    path('about/', about, name='about'),
]

mysite/joblist/urls.py
from django.urls import path
from . import views


app_name = 'joblist'
urlpatterns = [
    path('', views.JobList.as_view(), name="home"),
    path('update/', views.jobCrawler, name="crawler"),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('finance/', include('finance.urls')),
    path('users/', include('users.urls')),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('joblist/', include('joblist.urls')),
    path('polls/', include('polls.urls')),
    path('crypto/', include('crypto.urls')),
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/shop/urls.py
from django.urls import path
from .views import HomeView


app_name = 'shop'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

mysite/shop/models.py
from django.db import models
from django.shortcuts import reverse


CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField(default='1')
    description = models.TextField(default=' ')
    image = models.ImageField(default=' ')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

mysite/shop/views.py
from django.shortcuts import render
from .models import Item
from django.views.generic import ListView, DetailView, View


class HomeView(ListView):
    model = Item
    paginate_by = 10

mysite/shop/templates/shop/item_list.html
{% extends 'homepage/base.html' %}

{% block content %}

<div class="jumbotron">
    <h1 class="display-4">Here to find jobs!</h1>
    <p class="lead">Your Source OF SEEK JOBS</p>
    <a href="{% url 'joblist:crawler' %}">Update</a>
</div>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Company</th>
            <th scope="col">Location</th>
            <th scope="col">Date Expried</th>
        </tr>
    </thead>
    <tbody>
        {% for job in object_list %}
        <tr>
            <td>{{ job.title }}</td>
            <td>{{ job.company }}</td>
            <td>{{ job.location }}</td>
            <td>{{ job.date }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}