mysite/blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView, about


app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='delete'),
    path('post/new/', PostCreateView.as_view(), name='create'),
    path('about/', about, name='about'),
]

mysite/crypto/urls.py
from django.urls import path
from . import views


app_name = 'crypto'
urlpatterns = [
    path('', views.home, name="home"),
    path('price/', views.prices, name="prices"),
]

mysite/homepage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'
urlpatterns = [
    path('', views.home, name="home"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('finance/', include('finance.urls')),
    path('users/', include('users.urls')),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('joblist/', include('joblist.urls')),
    path('polls/', include('polls.urls')),
    path('crypto/', include('crypto.urls')),
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/users/urls.py
from django.urls import path
from .views import register, profile
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView

app_name = 'user'
urlpatterns = [
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html'), name='password-reset'),
    path('password-reset/done', PasswordResetView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/<uidb64>/<token>', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/blog/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})

mysite/blog/templates/blog/about.html
{% extends 'homepage/base.html' %}
{% block content %}
<h1>About Page</h1>
{% endblock content %}

mysite/blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

	{% if title %}
	<title>{{ title }}</title>
	{% else %}
	<title>Blog</title>
	{% endif %}
</head>

<body>
	<header class="site-header">
		<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
			<div class="container">
				<a class="navbar-brand mr-4" href="{% url 'homepage:home' %}">My LAB</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
					aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarToggle">
					<div class="navbar-nav mr-auto">
						<a class="nav-item nav-link" href="{% url 'homepage:home' %}">Home</a>
						<a class="nav-item nav-link" href="{% url 'crypto:home' %}">Crypto</a>
						<a class="nav-item nav-link" href="{% url 'polls:index' %}">Polls</a>
						<a class="nav-item nav-link" href="{% url 'blog:home' %}">Blog</a>
						<a class="nav-item nav-link" href="{% url 'blog:about' %}">About</a>
					</div>
					<!-- Navbar Right Side -->
					<div class="navbar-nav">
						{% if user.is_authenticated %}
						<a class="nav-item nav-link" href="{% url 'blog:create' %}">New Post</a>
						<a class="nav-item nav-link" href="{% url 'user:profile' %}">Profile</a>
						<a class="nav-item nav-link" href="{% url 'user:logout' %}">Logout</a>

						{% else %}
						<a class="nav-item nav-link" href="{% url 'user:login' %}">Login</a>
						<a class="nav-item nav-link" href="{% url 'user:register' %}">Register</a>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>
	</header>
	<main role="main" class="container">
		<div class="row">
			<div class="col-md-8">
				{% if messages %}
				{% for message in messages %}
				<div class="alert alert-{{ message.tags}}">
					{{message}}
				</div>
				{% endfor %}
				{% endif %}
				{% block content %}{% endblock %}
			</div>
			<div class="col-md-4">
				<div class="content-section">
					<h3>Our Sidebar</h3>
					<p class='text-muted'>You can put any information here you'd like.
						<ul class="list-group">
							<li class="list-group-item list-group-item-light">Latest Posts</li>
							<li class="list-group-item list-group-item-light">Announcements</li>
							<li class="list-group-item list-group-item-light">Calendars</li>
							<li class="list-group-item list-group-item-light">etc</li>
						</ul>
					</p>
				</div>
			</div>
		</div>
	</main>
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
		integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
		integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
		crossorigin="anonymous"></script>
</body>

</html>

mysite/blog/templates/blog/home.html
{% extends 'homepage/base.html' %}
{% block content %}
{% for post in posts %}
<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
	<div class="media-body">
		<div class="article-metadata">
			<a class="mr-2" href="{% url 'blog:user-posts'  post.author.username %}">{{ post.author }}</a>
			<small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
		</div>
		<h2><a class="article-title" href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h2>
		<p class="article-content">{{ post.content }}</p>
	</div>
</article>
{% endfor %}

{% if is_paginated %}
{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
<a class="btn btn-outline-info mb-4" href={{ page_obj.previous_page_number }}>Previous</a>
{% endif %}
{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}
{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}"">Next</a>
<a class=" btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}"">Last</a>
{% endif %}
{% endif %}
{% endblock content %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends 'homepage/base.html' %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'blog:detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

mysite/blog/templates/blog/post_detail.html
{% extends 'homepage/base.html' %}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'blog:user-posts'  object.author.username %}">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
            {% if object.author == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:update' object.id %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:delete' object.id %}">Delete</a>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">{{ object.content }}</p>
    </div>
</article>
{% endblock content %}

mysite/blog/templates/blog/post_form.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Blog Post</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Post</button>
        </div>
    </form>
</div>
{% endblock content %}

mysite/blog/templates/blog/user_posts.html
{% extends 'homepage/base.html' %}
{% block content %}
<h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
{% for post in posts %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'blog:user-posts'  post.author.username %}">{{ post.author }}</a>
            <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}

{% if is_paginated %}
{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
<a class="btn btn-outline-info mb-4" href={{ page_obj.previous_page_number }}>Previous</a>
{% endif %}
{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}
{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}"">Next</a>
<a class=" btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}"">Last</a>
{% endif %}
{% endif %}
{% endblock content %}